### ISSUE TITLE
Feature Request: Run concurrently

### ISSUE THREAD

**Issue by DillonStreator** [mikestead/lighthouse-batch#49] opened 2020-10-17 18:45 UTC
Are you open to a pull request for adding concurrency?
The thought is to allow a parameter `-c`  which would chunk sites and execute concurrently?

**Comment by mikestead** [comment] 2020-10-17 21:19
@DillonStreator Thanks for the offering to contribute.

The reason I never went down this path is that for each run you want to have the most identical environment, to ensure improvements or regressions are tracked accurately.

By parallelizing runs they can each start impacting one another, increasing result variability and the chance of false positives.

You can see a similar comment around this from a Google dev here https://github.com/GoogleChrome/lighthouse/issues/3837#issuecomment-573849468

For this reason I'm concerned such an option could introduce more issues than it solves.

Happy to hear your thoughts though.

**Comment by DillonStreator** [comment] 2020-10-17 21:21
Thank you for the info!
I actually just wrote a small wrapper around this library to concurrently run the audits and I'm getting very odd results, so this definitely helps explain why.

**Comment by mikestead** [comment] 2020-10-17 21:50
ok going to close this one off then cheers

**Closed by mikestead** 2020-10-17 21:50 UTC
